投稿フォームにNSFWガイドラインへの導線を追加
MisskeyIO/misskey pull request #182
Opened 2023-10-13 16:51 UTC by CyberRex0

## What
投稿フォームにNSFWガイドラインへの導線を追加

## Why
NSFWガイドラインをより周知させるため

## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2023-10-13 16:58 UTC, u1-liquid approved these changes
案内文とリンクがハードコーディングで変更時にはコードの修正が要るってこと以外は大丈夫そう
変更の頻度が高い文章ではないはずだしこれでいいかな

2023-10-14 02:04 UTC, riku6460 commented on packages/frontend/src/components/MkPostForm.vue
> +const nsfwGuideUrl = 'https://support.misskey.io/hc/ja/articles/6657417016463';
go.misskey.io のリンク発行してもらうのが良いかも？

2023-10-14 02:16 UTC, u1-liquid requested changes

2023-10-14 02:16 UTC, u1-liquid commented on packages/frontend/src/components/MkPostForm.vue
> +const nsfwGuideUrl = 'https://support.misskey.io/hc/ja/articles/6657417016463';
```suggestion
const nsfwGuideUrl = 'https://go.misskey.io/media-guideline';
```

2023-10-14 14:02 UTC, u1-liquid approved these changes

2023-10-15 01:09 UTC, riku6460 approved these changes

2023-10-16 08:29 UTC, merged