feat: 通報のカテゴリー化
MisskeyIO/misskey pull request #288
Opened 2023-12-22 17:11 UTC by CyberRex0

## What
通報のカテゴリー化を行う。あらかじめ設定された選択肢から理由を選んで通報することができる。

## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2023-12-26 05:13 UTC, riku6460 requested changes

2023-12-27 23:31 UTC, u1-liquid commented
最新にrebaseお願いします🙇

2023-12-28 01:53 UTC, u1-liquid approved these changes

2023-12-28 02:03 UTC, u1-liquid requested changes

2023-12-28 02:03 UTC, u1-liquid commented on packages/frontend/src/components/MkAbuseReportWindow.vue
> +				<MkButton @click="muteUser" :disabled="fullUserInfo?.isMuted">{{ i18n.ts.muteThisUser }}</MkButton>
```suggestion
				<MkButton :disabled="fullUserInfo?.isMuted" @click="muteUser">{{ i18n.ts.muteThisUser }}</MkButton>
```

2023-12-28 02:03 UTC, u1-liquid commented on packages/frontend/src/components/MkAbuseReportWindow.vue
> +				<MkButton @click="blockUser" :disabled="fullUserInfo?.isBlocking">{{ i18n.ts.blockThisUser }}</MkButton>
```suggestion
				<MkButton :disabled="fullUserInfo?.isBlocking" @click="blockUser">{{ i18n.ts.blockThisUser }}</MkButton>
```

2023-12-28 02:04 UTC, u1-liquid approved these changes

2023-12-28 02:23 UTC, u1-liquid requested changes

2023-12-28 02:23 UTC, u1-liquid commented on packages/backend/src/models/AbuseUserReport.ts
> +	public category: string;
```suggestion
	@Index()
	@Column('varchar', {
		length: 20, nullable: false,
		default: 'other',
	})
	public category: string;
```

2023-12-28 02:23 UTC, u1-liquid commented on packages/backend/migration/1703250468098-abuse-user-report-category.js
> +			await queryRunner.query(`ALTER TABLE "abuse_user_report" ALTER "category" SET NOT NULL`);
```suggestion
			await queryRunner.query(`ALTER TABLE "abuse_user_report" ADD "category" character varying(20) NOT NULL DEFAULT 'other'`);
			await queryRunner.query(`CREATE INDEX "IDX_5b9acc09094daeb8683e362778" ON "abuse_user_report" ("category") `);
```

2023-12-28 02:23 UTC, u1-liquid commented on packages/backend/migration/1703250468098-abuse-user-report-category.js
> +			await queryRunner.query(`ALTER TABLE "abuse_user_report" DROP COLUMN "category"`);
```suggestion
			await queryRunner.query(`DROP INDEX "public"."IDX_5b9acc09094daeb8683e362778"`);
			await queryRunner.query(`ALTER TABLE "abuse_user_report" DROP COLUMN "category"`);
```

2023-12-28 02:28 UTC, u1-liquid approved these changes
もう大丈夫だと思う
勝手にやったこと
* lintのチェックが落ちてたので直した
* 検索に使うのでindexを張った

2023-12-28 02:49 UTC, u1-liquid commented on locales/ja-JP.yml
> +reportComplete: "通報完了"
```suggestion
reportComplete: "ご協力いただき、ありがとうございます。"
```
こっちのほうがよさそう

2023-12-28 03:00 UTC, u1-liquid commented on locales/ja-JP.yml
> +reportComplete: "通報完了"
コード読み間違えた

2023-12-28 03:14 UTC, riku6460 approved these changes

2023-12-28 03:16 UTC, merged