enhance(backend): 投票の選択肢に対してもセンシティブワード検出を行うように
MisskeyIO/misskey pull request #630
Opened 2024-05-15 14:48 UTC by CyberRex0

## What
センシティブワードの検出を投票の選択肢に対しても行うようにした。

## Additional info (optional)

## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-05-15 15:44 UTC, riku6460 commented on packages/backend/src/core/NoteCreateService.ts
> +				for (let pci = 0; pci < data.poll.choices.length; pci++) {
動作自体はかわらないですけど、`for (const choice of data.poll.choices)` のほうが良いかなと思った

2024-05-16 13:05 UTC, riku6460 commented on packages/backend/src/core/NoteCreateService.ts
> +				for (let pci = 0; pci < data.poll.choices.length; pci++) {
ナイス break

2024-05-16 13:05 UTC, riku6460 approved these changes

2024-05-16 19:57 UTC, u1-liquid requested changes

2024-05-16 19:57 UTC, u1-liquid commented on packages/backend/src/core/NoteCreateService.ts
> +				for (const choice of data.poll.choices) {
ループにしちゃうと評価コストの高い正規表現などをN*m回回すことになるのであまりよろしくないかも
すぐ下の`checkProhibitedWordsContain()`の実装で使ってる`this.utilityService.concatNoteContentsForKeyWordCheck()`で最初の`if (this.utilityService.isKeyWordIncluded(data.cw ?? data.text ?? '', sensitiveWords))`の評価と統合したい
`checkProhibitedWordsContain`とは違って一旦CWにしているのであればOKってことにしたいので、`data.cw ?? concatNoteContentsForKeyWordCheck({text, pollChoices})`が理想かな

2024-05-18 11:31 UTC, CyberRex0 commented on packages/backend/src/core/NoteCreateService.ts
> +				for (const choice of data.poll.choices) {
`if (!data.cw && concatNoteContentsForKeyWordCheck({text: data.text, pollChoices: data.poll.choices})) ...` ？

2024-05-18 11:56 UTC, nenohi commented on packages/backend/src/core/NoteCreateService.ts
> +			if (data.poll) {
上の方で
data.visibility = 'home';
にしている部分があるのでdata.visibilityのpublicチェックもしたほうがいいんじゃないかな？

2024-05-18 13:09 UTC, u1-liquid commented on packages/backend/src/core/NoteCreateService.ts
> +				for (const choice of data.poll.choices) {
CWのキーワードがホーム送り対象ならホーム送りになるべきだからそれは違う

2024-05-18 13:13 UTC, u1-liquid commented on packages/backend/src/core/NoteCreateService.ts
> +				for (const choice of data.poll.choices) {
`if (this.utilityService.isKeyWordIncluded(data.cw ?? concatNoteContentsForKeyWordCheck({text, pollChoices}), sensitiveWords))`
こう

2024-05-20 11:03 UTC, CyberRex0 commented on packages/backend/src/core/NoteCreateService.ts
> +				for (const choice of data.poll.choices) {
直してみた

2024-05-20 23:36 UTC, u1-liquid approved these changes

2024-05-21 03:11 UTC, nenohi approved these changes

2024-05-22 12:55 UTC, merged