お知らせをDiscord側に通知するように
MisskeyIO/misskey pull request #635
Opened 2024-05-19 17:43 UTC by nenohi

## What

お知らせ発行時にDiscord側に通知するように修正
## Why

## Additional info (optional)

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-05-19 17:58 UTC, u1-liquid commented
```
pnpm clean; pnpm -r build:tsc; pnpm build; pnpm build-misskey-js-with-types
```
走らせてmisskey-js更新してください

2024-05-19 18:00 UTC, u1-liquid requested changes

2024-05-19 18:00 UTC, u1-liquid commented on packages/frontend/src/pages/admin/external-services.vue
> +		} else {
discordWebhook設定しないとdeeplも設定できないのはおかしいです

2024-05-19 18:22 UTC, nenohi commented on packages/frontend/src/pages/admin/external-services.vue
> +		} else {
URLチェックそもそもいらないかな？

2024-05-19 21:47 UTC, u1-liquid commented
こう実装すると後々の拡張性が皆無で他の変更とかも転送したくなったりslackとかにwebhook飛ばしたくなったりしたとき全部リワークになりそうだけど本当にこれでいいんだろうかね

できれば通報のwebhook同様既存のwebhook設定に組み込みたい気持ちがある
もしくは https://redirect.github.com/misskey-dev/misskey/pull/13758 のチェリーピック＆追加修正とか

2024-05-19 22:16 UTC, nenohi commented
確かにDiscordとしか考えてないけどMessageとかも全部諸々変更になるからめんどくさそう

2024-05-19 22:43 UTC, nenohi commented
既存のWebhook設定使ってもどこかしらで形式の変更が必要になるんじゃないかな？
Discordは
```
{
  content:"内容"
}
```
になるけど、既存のもの使うと
```
{
   updatedAt: null,
  title: ps.title,
  text: ps.text,
  imageUrl: ps.imageUrl,
  icon: ps.icon,
  display: ps.display,
  forExistingUsers: ps.forExistingUsers,
  needConfirmationToRead: ps.needConfirmationToRead,
  closeDuration: ps.closeDuration,
  displayOrder: ps.displayOrder,
  silence: ps.silence,
  userId: ps.userId,
}
```
が送信されてしまうので何かしらを噛ませないとDisocrd側に通知されなさそうな気がしてる

2024-05-20 23:59 UTC, u1-liquid commented
webhookにtypeフィールド追加して分岐させるとかがいいんじゃないかなと

2024-05-21 03:10 UTC, nenohi commented
Discord、Slack、Otherにして
Otherだったら詳細な部分できるようにして入力させるとかです？

2024-05-22 12:58 UTC, u1-liquid commented
そういう感じでよさそう
otherよりはtailscaleみたいにnone https://tailscale.com/kb/1213/webhooks#setting-up-a-webhook-endpoint とかmisskeyって名前がいいかもしれない

2024-05-28 10:32 UTC, nenohi commented
> できれば通報のwebhook https://github.com/MisskeyIO/misskey/pull/615 同様に既存のwebhook設定に組み込みたい気持ちがある

こっちで行ったほうが修正しやすそうなのでこれで

2024-05-28 10:44 UTC, nenohi commented
修正めんどくさいのでブランチ破壊して新しくPR建てますね

2024-05-28 10:44 UTC, closed without merging