api/usersに+pv -pvを追加
MisskeyIO/misskey pull request #653
Opened 2024-06-18 18:55 UTC by nenohi

## What

見つけるからUserを探す際に必要なAPIを先に追加
## Why

## Additional info (optional)

ローカルでテストしたけどユーザー数が少ないので一旦PR
良さそうであれば別PRで`見つける`のソートを変更します
## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-06-20 17:36 UTC, u1-liquid requested changes

2024-06-20 17:36 UTC, u1-liquid commented on packages/backend/src/server/api/endpoints/users.ts
> +			const chartUsers = await this.perUserPvChart.getChartUsers('hour', 0, null, ps.limit, ps.offset);
pv条件じゃない場合もuserpvchartをfetchすることになるのは避けたいかも

2024-06-20 17:46 UTC, nenohi commented on packages/backend/src/server/api/endpoints/users.ts
> +			const chartUsers = await this.perUserPvChart.getChartUsers('hour', 0, null, ps.limit, ps.offset);
endWithで判定入れてみた

2024-07-03 03:48 UTC, nenohi commented
ping

2024-07-12 16:50 UTC, u1-liquid approved these changes

2024-07-12 16:50 UTC, merged