feat(backend): elasticsearchで検索できるように
MisskeyIO/misskey pull request #661
Opened 2024-07-12 19:56 UTC by mattyatea

## What

ElasticSearchで検索できるようにしました
## Why

#502
## Additional info (optional)

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-07-12 22:22 UTC, u1-liquid requested changes

2024-07-12 22:22 UTC, u1-liquid commented on packages/backend/src/core/SearchService.ts
> +import type { Client as ElasticSearch } from '@elastic/elasticsearch';
```suggestion
import type { Client as ElasticSearch } from '@elastic/elasticsearch';

```
importの下の改行は残してほしい

2024-07-12 22:22 UTC, u1-liquid commented on packages/backend/src/core/SearchService.ts
> +	private elasticsearchNoteIndex: string | null = null;
```suggestion
	private elasticsearchNoteIndex: string | null = null;

```
メンバー変数の定義の下の改行は残してほしい

2024-07-12 22:22 UTC, u1-liquid commented on packages/backend/src/core/SearchService.ts
> +						console.error(error);
consoleのログはほとんど確認できないためLoggerService持ってきてちゃんとログに残るようにしてほしい
例: 
https://github.com/MisskeyIO/misskey/blob/488136582fab31aaa6ccaf5982f60ecaa7f79c5b/packages/backend/src/core/NoteCreateService.ts#L219
https://github.com/MisskeyIO/misskey/blob/488136582fab31aaa6ccaf5982f60ecaa7f79c5b/packages/backend/src/core/NoteCreateService.ts#L276

2024-07-12 22:22 UTC, u1-liquid commented on packages/backend/src/core/SearchService.ts
>  		}
上のブロックがif-elseなったのでmeilisearchのブロックの中に入れちゃっていいかも

2024-07-13 10:20 UTC, u1-liquid approved these changes

2024-07-13 21:27 UTC, riku6460 approved these changes

2024-07-13 22:18 UTC, merged