チュートリアルが特定の操作でスキップできてしまうのを修正
MisskeyIO/misskey pull request #674
Opened 2024-07-24 05:37 UTC by CyberRex0

## What
チュートリアルが特定の操作を行うとスキップできてしまうのを修正。

## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-07-24 10:17 UTC, riku6460 requested changes
そのままだと閉じられないけど一度何らかの要素を選択してから Esc で閉じられるっぽい

2024-07-24 10:37 UTC, CyberRex0 commented
これはもうMkModalWindowを改造するしかないね

2024-07-27 18:30 UTC, u1-liquid commented
どうします？

2024-07-28 00:43 UTC, CyberRex0 commented
本家側で閉じるボタン非表示やESCキーで閉じれないようにするオプションをMkModalWindowに追加してもらうことになった

2024-08-14 00:01 UTC, merged