凍結されたユーザー・削除されたユーザーを可視化できるように
MisskeyIO/misskey pull request #676
Opened 2024-07-27 12:33 UTC by nenohi

## What

## Why

## Additional info (optional)

## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-07-27 12:42 UTC, nenohi commented
テスト書き直すか

2024-07-27 12:52 UTC, nenohi commented
そもそもテストがテストしてないんじゃないかこれ
  ● ユーザー › をハッシュタグ指定で取得することができ、結果に削除済(byAdmin)ユーザーが含まれる

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      200
    Received:
      404

2024-07-27 13:19 UTC, nenohi commented
あーこれモデレーターからもユーザーがいないことになってしまうのか

2024-07-27 18:03 UTC, nenohi commented
色々テストが壊れそうなので書きます

2024-07-27 18:37 UTC, u1-liquid commented
`user.isDeleted`は元々「このユーザーは削除処理中である」というフラグで、本家のMisskeyの実装では削除が正常に終わるとDBからユーザーのrecordが消えるため、このフィールドをみて「削除済みのユーザー」かを判断するのは難しい
io独自の仕様で、ロールでアカウントの削除ができないユーザーの場合に限って、`user.isSuspended`+`user.isDeleted`状態になるため、有効なユーザーを探すクエリーは基本的には`user.isSuspended=false`だけでいいです

モデレーターのための実装に関してはAPIかentityserviceの中の分岐でisDeletedを見るようにしてほしい

2024-07-27 18:40 UTC, u1-liquid commented on packages/backend/src/server/api/endpoints/users/show.ts
> +				if (!isModerator && user.isDeleted) {
`user.isSuspended && user.isDeleted`のみが「削除済み」のユーザーです。
アカウント削除の権限を持っているユーザーの場合実際のrecordが消えるためこの実装は削除待機中のユーザーが巻き込まれるものになります

2024-07-30 05:25 UTC, nenohi commented
一旦できたかもしれない

2024-07-30 22:53 UTC, u1-liquid commented on packages/backend/src/server/api/endpoints/users/show.ts
> +					throw new ApiError(meta.errors.userNotFound);
物理削除と論理削除の区分を権限を持ってないユーザーもエラーコードで見分けられてしまう構造になってるので憶測が広まる可能性があるため両方`noSuchUser`で統一してほしい

2024-07-31 09:49 UTC, nenohi commented on packages/backend/src/server/api/endpoints/users/show.ts
> +					throw new ApiError(meta.errors.userNotFound);
エラーどころかページが変わるんだけど・・・

2024-07-31 10:01 UTC, nenohi commented on packages/backend/src/server/api/endpoints/users/show.ts
> +					throw new ApiError(meta.errors.userNotFound);
あーそういうことか理解した

2024-08-01 05:35 UTC, nenohi commented on packages/backend/src/server/api/endpoints/users/show.ts
> +					throw new ApiError(meta.errors.userNotFound);
修正した

2024-08-06 19:13 UTC, u1-liquid requested changes
format

2024-08-06 19:13 UTC, u1-liquid commented on packages/backend/src/server/api/endpoints/users/show.ts
> +			httpStatusCode: 404,
```suggestion
			httpStatusCode: 403,
```

2024-08-06 19:13 UTC, u1-liquid commented on packages/backend/src/server/api/endpoints/users/show.ts
> +				if (!isModerator) {
```suggestion
				}

				if (!isModerator) {
```

2024-08-06 19:13 UTC, u1-liquid commented on packages/backend/test/e2e/users.ts
> +	test('(Admin)が凍結済みユーザー情報を取得できる', async () => {
```suggestion
	});

	test('(Admin)が凍結済みユーザー情報を取得できる', async () => {
```

2024-08-06 19:13 UTC, u1-liquid commented on packages/frontend/src/pages/user/index.vue
> +	}>(), {
```suggestion
	acct: string;
	page?: string;
}>(), {
```

2024-08-06 19:13 UTC, u1-liquid commented on packages/frontend/src/pages/user/index.vue
> +const userstatus = ref<null | any >(null);
```suggestion
const error = ref<null | any>(null);
const userstatus = ref<null | any>(null);
```

2024-08-06 19:13 UTC, u1-liquid commented on packages/frontend/src/pages/user/index.vue
> +			userstatus.value = 'suspended';
```suggestion
		if (err.id && err.id === '4362f8dc-731f-4ad8-a694-be5a88922a24') { // User not found
			userstatus.value = 'notfound';
		} else if (err.id && err.id === 'c1e1b0d6-2b7c-4c1d-9f1d-2d3d6e8d7e7f') { // User suspended
			userstatus.value = 'suspended';
```

2024-08-06 19:14 UTC, u1-liquid approved these changes

2024-08-06 19:42 UTC, u1-liquid commented on packages/backend/test/e2e/users.ts
> +			{ status: 404, code: 'USER_SUSPENDED', id: 'c1e1b0d6-2b7c-4c1d-9f1d-2d3d6e8d7e7f' });
```suggestion
			{ status: 403, code: 'USER_SUSPENDED', id: 'c1e1b0d6-2b7c-4c1d-9f1d-2d3d6e8d7e7f' });
```
修正漏れ

2024-08-06 19:46 UTC, u1-liquid reviewed
削除関連のテストのコメントアウト解除

2024-08-06 19:46 UTC, u1-liquid commented on packages/backend/test/e2e/users.ts
> +		// { label: '削除済(byAdmin)ユーザーが含まれる', user: () => userDeletedByAdmin },
```suggestion
		{ label: '削除済ユーザーが含まれる', user: () => userDeletedBySelf },
		{ label: '削除済(byAdmin)ユーザーが含まれる', user: () => userDeletedByAdmin },
```

2024-08-06 19:46 UTC, u1-liquid commented on packages/backend/test/e2e/users.ts
> +		// { label: '自分以外から見たときは削除済み(byAdmin)か判定できない', user: () => userDeletedByAdmin, selector: (user: misskey.entities.UserDetailedNotMe) => user.isDeleted, expected: () => undefined },
```suggestion
		{ label: '削除済みになっている', user: () => userDeletedBySelf, me: () => userDeletedBySelf, selector: (user: misskey.entities.MeDetailed) => user.isDeleted },
		// @ts-expect-error UserDetailedNotMe doesn't include isDeleted
		{ label: '自分以外から見たときは削除済みか判定できない', user: () => userDeletedBySelf, selector: (user: misskey.entities.UserDetailedNotMe) => user.isDeleted, expected: () => undefined },
		{ label: '削除済み(byAdmin)になっている', user: () => userDeletedByAdmin, me: () => userDeletedByAdmin, selector: (user: misskey.entities.MeDetailed) => user.isDeleted },
		// @ts-expect-error UserDetailedNotMe doesn't include isDeleted
		{ label: '自分以外から見たときは削除済み(byAdmin)か判定できない', user: () => userDeletedByAdmin, selector: (user: misskey.entities.UserDetailedNotMe) => user.isDeleted, expected: () => undefined },
```

2024-08-06 19:46 UTC, u1-liquid commented on packages/backend/test/e2e/users.ts
> +		// { label: '削除済(byAdmin)ユーザーが含まれる', user: () => userDeletedByAdmin },
```suggestion
		{ label: '削除済ユーザーが含まれる', user: () => userDeletedBySelf },
		{ label: '削除済(byAdmin)ユーザーが含まれる', user: () => userDeletedByAdmin },
```

2024-08-06 19:46 UTC, u1-liquid commented on packages/backend/test/e2e/users.ts
> +		// { label: '削除済(byAdmin)ユーザーが含まれる', user: () => userDeletedByAdmin },
```suggestion
		{ label: '削除済ユーザーが含まれる', user: () => userDeletedBySelf },
		{ label: '削除済(byAdmin)ユーザーが含まれる', user: () => userDeletedByAdmin },
```

2024-08-06 19:46 UTC, u1-liquid commented on packages/backend/test/e2e/users.ts
> +		// { label: '削除済(byAdmin)ユーザーが含まれる', user: () => userDeletedByAdmin },
```suggestion
		{ label: '削除済ユーザーが含まれる', user: () => userDeletedBySelf },
		{ label: '削除済(byAdmin)ユーザーが含まれる', user: () => userDeletedByAdmin },
```

2024-08-06 19:46 UTC, u1-liquid commented on packages/backend/test/e2e/users.ts
> +		// { label: '削除済(byAdmin)ユーザーが含まれる', user: () => userDeletedByAdmin },
```suggestion
		{ label: '削除済ユーザーが含まれる', user: () => userDeletedBySelf },
		{ label: '削除済(byAdmin)ユーザーが含まれる', user: () => userDeletedByAdmin },
```

2024-08-06 19:46 UTC, u1-liquid commented on packages/backend/test/e2e/users.ts
> +		// { label: '削除済(byAdmin)ユーザーが含まれる', user: () => userDeletedByAdmin },
```suggestion
		{ label: '削除済ユーザーが含まれる', user: () => userDeletedBySelf },
		{ label: '削除済(byAdmin)ユーザーが含まれる', user: () => userDeletedByAdmin },
```

2024-08-06 20:26 UTC, merged