Fixapiuser
MisskeyIO/misskey pull request #717
Opened 2024-08-22 03:59 UTC by nenohi

## What

pvのときに同じユーザーしか返ってこないので一旦hourからdayに変更
## Why

hourだと
## Additional info (optional)

ローカル環境のためユーザー不足で未実施
## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-08-22 09:35 UTC, u1-liquid requested changes

2024-08-22 09:35 UTC, u1-liquid commented on packages/backend/src/core/chart/charts/per-user-pv.ts
> +	public async getChartUsers(span: 'hour' | 'day', amount: number, cursor: Date | null, limit = 0, offset = 0, order: 'ASC' | 'DESC'): Promise<{
Code Analysisの指摘通りorderパラメータをdefault値の指定されているlimit, offsetの後ろに置くことは問題なので直してください
```suggestion
	public async getChartUsers(span: 'hour' | 'day', amount: number, order: 'ASC' | 'DESC', cursor: Date | null, limit = 0, offset = 0): Promise<{
```

2024-08-22 10:36 UTC, riku6460 commented on packages/backend/src/server/api/endpoints/users.ts
> +					});
インデントが破壊されている

2024-08-22 14:31 UTC, 6wFh3kVo commented
そうだそうだ～！

2024-08-24 08:52 UTC, riku6460 commented on packages/backend/src/core/chart/core.ts
> +			.orderBy('___pv_visitor + ___upv_visitor + ___pv_user + ___upv_user', order === 'ASC' ? 'ASC' : 'DESC')
たぶん
```suggestion
			.orderBy('___pv_visitor + ___upv_visitor + ___pv_user + ___upv_user', order)
```

2024-08-24 10:59 UTC, u1-liquid commented
そもそものクエリーがちゃんと正常な値を作れてなさそう
データの正常なsumが行われてないので返り値のほとんどが0か1で埋もれてしまう

ちゃんとpostgresql上でsumしてgroupbyさせるように直した方がいいかも
以下は正常動作確認したクエリー、upv_user以外の値を参照する必要はないと思う
↑visitor(非ログインユーザー)やuniqueではないインプレッションを集計する意味はあまりないかも？

hours集計
```sql
select "group" as id, sum(___upv_user) as upv
from __chart__per_user_pv
where date between 1724490000 and 1724493600
group by "group"
order by upv desc
offset 0 limit 10;
```

days集計
```sql
select "group" as id, sum(___upv_user) as upv
from __chart_day__per_user_pv
where date between 1724425200 and 1724511600
group by "group"
order by upv desc
offset 0 limit 10;
```

2024-09-16 12:34 UTC, closed without merging