Enhance(Page): ページを非公開にできるように
MisskeyIO/misskey pull request #821
Opened 2024-11-20 15:49 UTC by mattyatea

## What

## Why

## Additional info (optional)

## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

2024-11-21 13:12 UTC, u1-liquid requested changes
非公開のことをpublishって呼ぶのは違う気がする
既にvisibilityフィールドがあるのでそれをdropせずにpublic/privateで扱ってほしい
frontendのpageの一覧で見分けがつかないので非公開状態のpageは非公開ってラベルを付けてほしい

2024-12-07 11:09 UTC, mattyatea commented
UIはこんな感じです
![image](https://github.com/user-attachments/assets/8bf6c889-8c0e-48d1-8189-be70474c7d44)
![image](https://github.com/user-attachments/assets/cf4ba605-7c48-492b-ba51-1f925ed01d79)
![image](https://github.com/user-attachments/assets/eca5fbd8-727d-494e-a8ba-994d480780ce)
![image](https://github.com/user-attachments/assets/07680c01-501e-4305-a887-98d77706fe49)

2024-12-07 11:11 UTC, mattyatea commented
あとPageの中とPagePreviewでタイトルの表示に差異があるのが気になったので直してます
![image](https://github.com/user-attachments/assets/7b55d935-cb8c-458b-a58c-afe20892929f)

2024-12-07 20:10 UTC, u1-liquid commented on locales/index.d.ts
> +    "isPublic": string;
```suggestion
```

2024-12-07 20:10 UTC, u1-liquid commented on locales/ja-JP.yml
> +isPublic: "公開"
```suggestion
```

2024-12-10 18:22 UTC, u1-liquid approved these changes

2024-12-10 18:23 UTC, merged